### ISSUE TITLE
erronous glpi_bookmarks calls

### ISSUE THREAD

**Issue by Stoatwblr** [ericferon/glpi-statecheck#10]
(This is actually across all your plugins)

glpi_bookmarks was renamed to glpi_savedsearches in 9.2
glpi_bookmarks_users renamed to glpi_savedsearches_users

[2019-01-24 14:35:01] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_bookmarks` WHERE `itemtype` LIKE 'PluginStatecheck%' ;
  Error: Table 'datatrieve.glpi_bookmarks' doesn't exist
  Backtrace :
  plugins/statecheck/hook.php:126
  inc/plugin.class.php:659                           plugin_statecheck_uninstall()
  front/plugin.form.php:47                           Plugin->uninstall()
  {"user":"11@msslyz.mssl.ucl.ac.uk"}

**Comment by ericferon** [comment]
Solved in v2.0.11.
Best regards,
