### ISSUE TITLE
/front/rule.form.php   HTTP ERROR 500

### ISSUE THREAD

**Issue by SilentBob999** [ericferon/glpi-statecheck#13]
Hi,
we install your plugin to explorer its possibility and see if it can fill some of our need with it.
Table seems fine but we cannot go add a rules.
The page "/plugins/statecheck/front/rule.form.php" give an http error 500.

We have statecheck v2.1.0 on GLPI 9.4.0

Thank you,

**Comment by SilentBob999** [comment]
tested with GLPI 9.4.4 with the same result. No sure how to diagnostic that more...

**Comment by ericferon** [comment]
I forgot to push a correction I was working with for several weeks ... Sorry.
It has been done in v2.1.1, just released.
Can you try ?
Thank you,

**Comment by SilentBob999** [comment]
Hi,  
we are now able to access and create a new "Statecheck Rules".  The "Criteria" and "Actions" page cannot be load.
Those are the error I got in debug mode;
Criteria page:
`Fatal error: Uncaught Error: Call to a member function fetch_assoc() on bool in /var/www/html/glpi/inc/dbmysql.class.php:330 Stack trace: #0 /var/www/html/glpi/plugins/statecheck/inc/ruleaction.class.php(314): DBmysql->fetch_assoc(false) #1 /var/www/html/glpi/plugins/statecheck/inc/rule.class.php(714): PluginStatecheckRuleAction->getStatecheckRuleActions('34') #2 /var/www/html/glpi/plugins/statecheck/inc/rule.class.php(2897): PluginStatecheckRule->getStatecheckRuleWithCriteriasAndActions('34', 1, 1) #3 /var/www/html/glpi/inc/commonglpi.class.php(485): PluginStatecheckRule::displayTabContentForItem(Object(PluginStatecheckRule), '1', '') #4 /var/www/html/glpi/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginStatecheckRule), 'PluginStatechec...', '', Array) #5 {main} thrown in /var/www/html/glpi/inc/dbmysql.class.php on line 330`
Action page:
`Fatal error: Uncaught Error: Call to a member function fetch_assoc() on bool in /var/www/html/glpi/inc/dbmysql.class.php:330 Stack trace: #0 /var/www/html/glpi/plugins/statecheck/inc/ruleaction.class.php(314): DBmysql->fetch_assoc(false) #1 /var/www/html/glpi/plugins/statecheck/inc/rule.class.php(714): PluginStatecheckRuleAction->getStatecheckRuleActions('34') #2 /var/www/html/glpi/plugins/statecheck/inc/rule.class.php(2897): PluginStatecheckRule->getStatecheckRuleWithCriteriasAndActions('34', 1, 1) #3 /var/www/html/glpi/inc/commonglpi.class.php(485): PluginStatecheckRule::displayTabContentForItem(Object(PluginStatecheckRule), '2', '') #4 /var/www/html/glpi/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginStatecheckRule), 'PluginStatechec...', '', Array) #5 {main} thrown in /var/www/html/glpi/inc/dbmysql.class.php on line 330`
Debug page:
`PHP Notice: Undefined index: uuid in /var/www/html/glpi/plugins/statecheck/inc/rule.class.php at line 2939
UUID: `
The rule I try to test is based on this table setup:
Name: glpi_budgets
Class: budget
State table: glpi_budgettypes
State class: budgettype
Frontname: budget

I also try to install the plugin on a test virtual machine which run a fresh GLPI 9.4.4 on a Windows server, and the "install" of the plugin give an Error 500.

Thank you,

**Comment by ericferon** [comment]
The classes are written in camel case : Budget and BudgetType.
When testing, I noticed that the controlled fields are not put in red, although the rule is well checked.
This is due to the way the budget fields are defined in HTML (different than in the other forms). I will solved that in a future version.
Best regards,

**Comment by SilentBob999** [comment]
Hi,
The fatal error I mention earlier : "The "Criteria" and "Actions" page cannot be load.".

It as those SQL request error :
Table 'glpi.glpi_plugin_statecheck_rulecriterias' doesn't exist
Table 'glpi.glpi_plugin_statecheck_ruleactions' doesn't exist

I actually do not have those table, should they not be created when we install the plugin?

Can I ask a question about the scope of your plugin? Can you tell me if it is possible to control fields within a form create by FormCreator?

Sorry for all the trouble.
Thank you,

**Comment by ericferon** [comment]
Yes, those 2 tables should have been created on plugin installation.
To create the tables, you can uninstall and reinstall the plugin (but you loose all the content of the statecheck rules) or you can execute the needed sql commands from statecheck/sql/empty1.0.0.sql
I'm not using FormCreator. So I don't now.
Best regards,

**Comment by ericferon** [comment]
The controlled fields not in red were due to my mistake in the rules set-up for budgets. This was not a bug.

**Comment by MichelCaron-IS** [comment]
Hi, 
manually run part of statecheck/sql/empty1.0.0.sql work.  
I believe it fail to create glpi_plugin_statecheck_rulecriterias & glpi_plugin_statecheck_ruleactions when run as a block because I do not have DataFlow and there is two insert that require glpi_plugin_dataflows_states which run before the creation of those two missing table...
Changing the order of execution could be a solution?
Thank you,
