### ISSUE TITLE
PHP User deprecated function (16384): Use DBmysql::fetchAssoc() in /var/www/html/g952/inc/toolbox.class.php at line 632

### ISSUE THREAD

**Issue by jairockman** [ericferon/glpi-statecheck#14]
Hi, I'm getting the error on the title when installing the plugin. The error only show in debug mode, but fill the file php-error.log a lot.

![image](https://user-images.githubusercontent.com/56606032/96610392-314c3c80-12c1-11eb-833f-a217319aad7a.png)

Also its appear in home /front/central.php
![image](https://user-images.githubusercontent.com/56606032/96611118-feef0f00-12c1-11eb-86d3-8a30cbd3f620.png)

The php-error.log

> *** PHP User deprecated function (16384): Use DBmysql::fetchAssoc() in /var/www/html/g952/inc/toolbox.class.php at line 632
  Backtrace :
  inc/toolbox.class.php:632                          trigger_error()
  inc/dbmysql.class.php:484                          Toolbox::deprecated()
  **plugins/statecheck/setup.php:58                    DBmysql->fetch_assoc()**
  inc/plugin.class.php:262                           plugin_init_statecheck()
  inc/plugin.class.php:224                           Plugin::load()
  inc/includes.php:106                               Plugin->init()
  plugins/actualtime/ajax/timer.php:3                include()

> *** PHP User deprecated function (16384): Use DBmysql::fetchAssoc() in /var/www/html/g952/inc/toolbox.class.php at line 632
  Backtrace :
  inc/toolbox.class.php:632                          trigger_error()
  inc/dbmysql.class.php:484                          Toolbox::deprecated()
  **plugins/statecheck/setup.php:58                    DBmysql->fetch_assoc()**
  inc/plugin.class.php:262                           plugin_init_statecheck()
  inc/plugin.class.php:224                           Plugin::load()
  inc/includes.php:106                               Plugin->init()
  ajax/dashboard.php:33                              include()

**GLPI 9.5.2
PHP 7.2.24-0ubuntu0.18.04.7
statecheck           Name: Statecheck Rules               Version: 2.2.1**

**Comment by ericferon** [comment]
Thank you for your issue report.
I replaced the deprecated function in the just released v2.2.2.
Kind regards,
