### ISSUE TITLE
Use case for user provisioning auto account creation

### ISSUE THREAD

**Issue by mrgeppetto** [ericferon/glpi-statecheck#15]
Hello,        Thank you for taking your time in creating these pretty interesting plugins. I was just wondering if there was a use case for this plugin as well as the dataflows plugin for auto creating accounts after SSO authentication. I have implemented the SSO plugin "edgardmessias/glpi-singlesignon". We are using one of our intranet sites acting as an IDP to authenticate users and are not using LDAP to import users. SSO works if a user has an account on both platforms but not if they only have an account on 1. The SSO plugin does not have any provisioning features so I was wondering if this could take over provisioning features.

**Comment by ericferon** [comment]
I have no idea how the glpi-singlesignon is working.
The "statecheck" plugin checks only the values in a GLPI form (this could be the user creation form), according to rules defined in the statecheck tables.
The "dataflows" plugin let you maintain an inventory of data exchanges between your applications. It does not provision data uploads.
K.r,
