### ISSUE TITLE
Issue in GLPI v10

### ISSUE THREAD

**Issue by jamesg1992** [ericferon/glpi-statecheck#17]
Hi,
when i installed the plugin in GLPI v10, didn't recognize the table

and it show a white screen, with no text in the page

Is it compatible with GLPI v10?

Thanks

**Comment by SI-AURAL** [comment]
Hi,

Same problem.
GLPI v10.0.2, Statecheck v2.3.4

From files/_logs/php-errors.php, there is this message :

> [2022-07-27 19:06:16] glpiphplog.CRITICAL:   *** Uncaught Exception Twig\Error\LoaderError: The "../../../templates" directory does not exist ("/srv/glpi/prod/../../../templates"). in /srv/glpi/prod/vendor/twig/twig/src/Loader/FilesystemLoader.php at line 92
  Backtrace :
  ...or/twig/twig/src/Loader/FilesystemLoader.php:78 Twig\Loader\FilesystemLoader->addPath()
  ...or/twig/twig/src/Loader/FilesystemLoader.php:45 Twig\Loader\FilesystemLoader->setPaths()
  ...od/src/Application/View/TemplateRenderer.php:71 Twig\Loader\FilesystemLoader->__construct()
  ...d/src/Application/View/TemplateRenderer.php:134 Glpi\Application\View\TemplateRenderer->__construct()
  /srv/glpi/prod/src/Html.php:1383                   Glpi\Application\View\TemplateRenderer::getInstance()
  /srv/glpi/prod/src/Html.php:1762                   Html::includeHeader()
  /srv/glpi/prod/src/CommonDBTM.php:6383             Html::header()
  /srv/glpi/prod/src/CommonDropdown.php:229          CommonDBTM::displayCentralHeader()
  /srv/glpi/prod/front/dropdown.common.php:50        CommonDropdown::displayCentralHeader()
  ...glpi/prod/plugins/statecheck/front/table.php:31 include()

**Comment by ericferon** [comment]
Hi,
I'm also running GLPI 10.0.2 now, and I don't get your error message.
Is it still the case for you ?
K.r,

**Comment by AlekseyBerez** [comment]
We have GLPI 10.0.2. and we have white screen, with no text in the page also.

**Comment by ericferon** [comment]
Hi,
If I refer to the SI-AURAL's error messages, it seems that the GLPI_ROOT/templates directory does not exist in the installation. I do not know why, but it should exist with a lot of GLPI standard files.
For the other ones, I haven't enough information to examine the problem.
So, I close this issue. Open a new one, with error messages, if you need help.
K.r,

**Comment by AlekseyBerez** [comment]
Hi, I installed v2.3.7. and error no more. v2.3.4 was erly
