### ISSUE TITLE
Fields not highlighted GLPI v10.0.3

### ISSUE THREAD

**Issue by FeluxSLSH** [ericferon/glpi-statecheck#18]
Hello! Please help, I want to make a check for the fields on the ticket form for certain fields, all the steps went through the guide, but the highlighting of the fields does not appear, only the notification "!! Highlighted fields are controlled !!". Tell me please, maybe I didn’t correctly specify the state table somewhere or defined the class incorrectly?
![image](https://user-images.githubusercontent.com/117974027/201862511-39bd0d0d-a648-4286-9e25-78b1440d2277.png)
![image](https://user-images.githubusercontent.com/117974027/201862683-6f20bb46-6104-4aba-ac2c-93775928e543.png)
![image](https://user-images.githubusercontent.com/117974027/201862775-a0e910f2-f310-4861-9645-fe8d3f55a7bf.png)
![image](https://user-images.githubusercontent.com/117974027/201862893-5e497da0-4c98-405e-a0b6-3f4504af6a89.png)
![image](https://user-images.githubusercontent.com/117974027/201863376-69c00339-756d-4904-94cf-af0299e92df6.png)

**Comment by ericferon** [comment]
Hi,
Indeed, I can repeat the problem.
The current ticket implementation seems not to follow the same development principles as the other core's or plugin's entities.
I will examine whether I can adapt my plugin, but I cannot commit to a solution in the short term.
K.r,

**Comment by ericferon** [comment]
Hi,
In fact, I cannot adapt my plugin, but you should adapt your "action" : if you put the value 5 instead of "Very high", it should work.
This is due to the fact that tickets don't use usual dropdown tables, but a function getPriorityName (in file CommonITILObject.php), with the following mapping :
    public static function getPriorityName($value)
    {

        switch ($value) {
            case 6:
                return _x('priority', 'Major');

            case 5:
                return _x('priority', 'Very high');

            case 4:
                return _x('priority', 'High');

            case 3:
                return _x('priority', 'Medium');

            case 2:
                return _x('priority', 'Low');

            case 1:
                return _x('priority', 'Very low');

           // No standard one :
            case 0:
                return _x('priority', 'All');
            case -1:
                return _x('priority', 'At least very low');
            case -2:
                return _x('priority', 'At least low');
            case -3:
                return _x('priority', 'At least medium');
            case -4:
                return _x('priority', 'At least high');
            case -5:
                return _x('priority', 'At least very high');

            default:
               // Return $value if not define
                return $value;
        }
    }
K.r,
