### ISSUE TITLE
DataInjection Plugin Checks

### ISSUE THREAD

**Issue by maunat** [ericferon/glpi-statecheck#22]
Is It possible to connect Statecheck' rules with the injected data via DataInjection Plugin?
I have defined a simple rule to check UUID field is not missing but when data has injected via DataInjection Plugin, Statecheck does not trigger its rules allowing the insert.

**Comment by ericferon** [comment]
Hi,
Not easily : the statecheck plugin is GUI-oriented, that is : it's working with Javascript and it's checking 1 record at a time.
Datainjection plugin is working in batch with several records. I don't think that there are hooks to integrate statecheck into datainjection .
K.r,

**Comment by maunat** [comment]
Hi,

Thanks a lot.

Could you please help me to understand how this kind of hook can be
developed?

Maurizio

Il ven 6 ott 2023, 18:11 Eric Feron ***@***.***> ha scritto:

**Comment by maunat** [comment]
Hi Ericferon/Glpi-Statecheck,

I guess I have reached the sky!
I have been able to integrate your code into DataInjection Core!! Now
DataInjection allows you to check all the rules provided by Statecheck.

In attachment, the updated script.

I guess I have to enable the desired behaviour only if the Statecheck
plugin is enabled now...

Let me know what you think, please! And if in this fashion it could be
released in the marketplace.

Thank you

M

Il giorno ven 6 ott 2023 alle ore 19:33 Maurizio Natalia <
***@***.***> ha scritto:

**Comment by ericferon** [comment]
Congratulations !
But I do not see any attachment.
Can you specify which plugin file you modified, with the line number and the content of the modification ?
If it's sustainable, I will integrate it in statecheck.
K.r,

**Comment by maunat** [comment]
Sorry about that.

So, I've made in your plugin effective modifications in order to support
the integration with the plugin: *Generic Object Plugin, *in the following
hooks: *plugin_pre_item_statecheck*, *hook_post_item_form.*
Then, I took your snippet of code (hook: *plugin_pre_item_statecheck*) and
integrated it into *Data Injection Plugin.*

I will explain the steps.

*1) Generic Object Plugin:*
*Statecheck breaks its behaviour in custom objects because of the 'object'
frontname.*
It means that the statecheck queries retrieve all the rules and the plugin
applies to all "/object" Objects. But this is not true because
different objects (created via Custom Object Plugin) have the same
frontname. So I modified your core putting a condition where *if the
frontname is 'object' the queries read the itemtype parameter *in
$_SERVER['HTTP_REFERER'] that is the *Class of Custom Object*. And then I
put the class itself as a frontname.

function plugin_pre_item_statecheck($item)
{
    ... after line 195
    # missing the check: if custom object plugin is enabled
    if($frontname == 'object') {
        parse_str(parse_url($_SERVER['HTTP_REFERER'])['query'], $output);
        $classname = $output['itemtype'];
        if (isset($classname)) {
            $frontname = $classname;
        }
    }
    ... before state query

then, in order to fix the red inputs in the object forms, I needed to
modify the following:

function hook_post_item_form(array $params) {
     global $DB, $_SERVER;

     if ($params['item']->canCreate()) {
         // check that the current form is listed for statecheck
         if (isset($_SERVER['HTTP_REFERER'])) {
             $start = strpos($_SERVER['HTTP_REFERER'],'/front') + 7;
             $end = strpos($_SERVER['HTTP_REFERER'],'.',$start);
             $frontname = substr($_SERVER['HTTP_REFERER'],$start,$end-$start);

             # 1. get here the classname to reuse it
             $classname = get_class($params['item']);

             # missing the check: if the custom object plugin is enabled
             # 2. check if frontname is 'object' and change frontname
             if ($frontname == 'object') {
                 $frontname = $classname;
             }

             $query = "select * from glpi_plugin_statecheck_tables
where frontname = '".$frontname."'";
             if ($result=$DB->query($query)) {
                 if ($DB->fetchAssoc($result)) {
                     $classname = $classname;
                     $statecheckrule = new PluginStatecheckRule;

$statecheckrule->plugin_statecheck_renderfields($classname);
                 }
             }
         }
     }
}

*So, these snippets of code have been modified into your Statecheck Plugin
Core.*

*2) Data Injection Object Plugin:*
What I did to "integrate" Statecheck into Data Injection Plugin it's quite
different:

I took the snippet of code in your *plugin_pre_item_statecheck *and I
adapted it to fit into the Data Injection Plugin with great results, at
least I guess.

So, in Data Injection Plugin into /inc/*commoninjectionlib.class.php *I
wrote the following (you can check it between two explicit comment):

public function processAddOrUpdate() {
   global $DB;
   $process  = false;
   $add      = true;
   $accepted = false;

   $this->values = Sanitizer::dbUnescapeRecursive($this->values);
   //Toolbox::logDebug("processAddOrUpdate(), start with", $this->values);

   // Initial value, will be change when problem
   $this->results['status']                     = self::SUCCESS;
   $this->results[self::ACTION_CHECK]['status'] = self::SUCCESS;


 /*-------------------------------------------------------------------------------------------------
     START DATAINJECTION INTEGRATION WITH STATECHECK
 -------------------------------------------------------------------------------------------------*/
   $firstKey = array_key_first($this->values);
   $currentValues = $this->values[$firstKey];

   $item = $currentValues;

 $queryrule = "SELECT `glpi_plugin_statecheck_rules`.`id`,
`glpi_plugin_statecheck_rules`.`name` as rulename,
`glpi_plugin_statecheck_tables`.`id` as tableid,
`glpi_plugin_statecheck_tables`.`name` as tablename,
`glpi_plugin_statecheck_tables`.`class` FROM
glpi_plugin_statecheck_rules, glpi_plugin_statecheck_tables WHERE
`glpi_plugin_statecheck_rules`.`plugin_statecheck_tables_id` =
`glpi_plugin_statecheck_tables`.`id` AND `frontname` LIKE '$firstKey'
AND `is_active` = 1";

 if ($resultrule=$DB->query($queryrule)) {
      if (is_array($item)) {
         $item['hookerror'] = false;
         if (isset($item['hookmessage']))
            unset($item['hookmessage']);
      } else {
         $item->hookerror = false;
         if (isset($item->hookmessage))
            unset($item->hookmessage);
      }
      $itemtype = "";
      while ($datarule=$DB->fetchAssoc($resultrule)) {
         $rules_id = $datarule['id'];
         $rules_name = $datarule['rulename'];
         $table_name = $datarule['tablename'];
         $table_id = $datarule['tableid'];
         $itemtype = $datarule['class'];
 //          for each rule, retrieve the pre-conditions to apply the rule
         $criteriacheck = true;
         $querycriteria = "SELECT * from
`glpi_plugin_statecheck_rulecriterias` WHERE
`plugin_statecheck_rules_id` = $rules_id";
         if ($resultcriteria=$DB->query($querycriteria)) {
            while ($datacriteria=$DB->fetchAssoc($resultcriteria)) {
               switch ($datacriteria['condition']) {
                  case Rule::PATTERN_IS :
                     if (is_array($item)) {
                        $criteriacheck &=
($item[$datacriteria['criteria']]==$datacriteria['pattern']?true:false);
                     } else if (isset($item->input[$datacriteria['criteria']]))
                        {
                           $criteriacheck &=
($item->input[$datacriteria['criteria']]==$datacriteria['pattern']?true:false);
                        }
                        else
                        {
                           $criteriacheck &=
($item->fields[$datacriteria['criteria']]==$datacriteria['pattern']?true:false);
                        }
                  break 1;
                  case Rule::PATTERN_IS_NOT :
                     if (is_array($item)) {
                        $criteriacheck &=
($item[$datacriteria['criteria']]!=$datacriteria['pattern']?true:false);
                     } else if (isset($item->input[$datacriteria['criteria']]))
                        {
                           $criteriacheck &=
($item->input[$datacriteria['criteria']]!=$datacriteria['pattern']?true:false);
                        }
                        else
                        {
                           $criteriacheck &=
($item->fields[$datacriteria['criteria']]!=$datacriteria['pattern']?true:false);
                        }
                  break 1;
                  case Rule::PATTERN_CONTAIN :
                  break 1;
                  case Rule::PATTERN_NOT_CONTAIN :
                  break 1;
                  case Rule::PATTERN_BEGIN :
                  break 1;
                  case Rule::PATTERN_END :
                  break 1;
                  case Rule::REGEX_MATCH :
                     if (is_array($item)) {
                        $criteriacheck &=
preg_match($datacriteria['pattern'],unclean_cross_side_scripting_deep($item[$datacriteria['criteria']]));
                     } else if (isset($item->input[$datacriteria['criteria']]))
                        {
                           $criteriacheck &=
preg_match($datacriteria['pattern'],unclean_cross_side_scripting_deep($item->input[$datacriteria['criteria']]));
                        }
                        else
                        {
                           $criteriacheck &=
preg_match($datacriteria['pattern'],unclean_cross_side_scripting_deep($item->fields[$datacriteria['criteria']]));
                        }
                  break 1;
                  case Rule::REGEX_NOT_MATCH :
                     if (is_array($item)) {
                        $criteriacheck &=
(preg_match($datacriteria['pattern'],unclean_cross_side_scripting_deep($item[$datacriteria['criteria']]))?false:true);
                     } else if (isset($item->input[$datacriteria['criteria']]))
                        {
                           $criteriacheck &=
(preg_match($datacriteria['pattern'],unclean_cross_side_scripting_deep($item->input[$datacriteria['criteria']]))?false:true);
                        }
                        else
                        {
                           $criteriacheck &=
(preg_match($datacriteria['pattern'],unclean_cross_side_scripting_deep($item->fields[$datacriteria['criteria']]))?false:true);
                        }
                  break 1;
                  case Rule::PATTERN_EXISTS :
                     if (substr($datacriteria['criteria'],-3) == '_id') {
                        if (is_array($item)) {
                           $criteriacheck &=
($item[$datacriteria['criteria']]!=0?true:false);
                        } else if
(isset($item->input[$datacriteria['criteria']]))
                           {
                              $criteriacheck &=
($item->input[$datacriteria['criteria']]!=0?true:false);
                           }
                           else
                           {
                              $criteriacheck &=
($item->fields[$datacriteria['criteria']]!=0?true:false);
                           }
                     } else {
                        if (is_array($item)) {
                           $criteriacheck &=
($item[$datacriteria['criteria']]!=""?true:false);
                        } else if
(isset($item->input[$datacriteria['criteria']]))
                           {
                              $criteriacheck &=
($item->input[$datacriteria['criteria']]!=""?true:false);
                           }
                           else
                           {
                              $criteriacheck &=
($item->fields[$datacriteria['criteria']]!=""?true:false);
                           }
                     }
                  break 1;
                  case Rule::PATTERN_DOES_NOT_EXISTS :
                     if (substr($datacriteria['criteria'],-3) == '_id') {
                        if (is_array($item)) {
                           $criteriacheck &=
($item[$datacriteria['criteria']]==0?true:false);
                        } else if
(isset($item->input[$datacriteria['criteria']]))
                           {
                              $criteriacheck &=
($item->input[$datacriteria['criteria']]==0?true:false);
                           }
                           else
                           {
                              $criteriacheck &=
($item->fields[$datacriteria['criteria']]==0?true:false);
                           }
                     } else {
                        if (is_array($item)) {
                           $criteriacheck &=
($item[$datacriteria['criteria']]==""?true:false);
                        } else if
(isset($item->input[$datacriteria['criteria']]))
                           {
                              $criteriacheck &=
($item->input[$datacriteria['criteria']]==""?true:false);
                           }
                           else
                           {
                              $criteriacheck &=
($item->fields[$datacriteria['criteria']]==""?true:false);
                           }
                     }
                  break 1;

                  default:
                  break 1;
               }
            }
         }
 //          if rule applies
         if ($criteriacheck) {
 //             retrieve the fields to check on behalf of this rule
and check the condition of the current field value
            $queryaction = "SELECT * from
`glpi_plugin_statecheck_ruleactions` WHERE
`plugin_statecheck_rules_id` = $rules_id";
            if ($resultaction=$DB->query($queryaction)) {
 //                get field name and label
               $ruleaction = new PluginStatecheckRuleAction;
               $fields = $ruleaction->getActionFields($table_id);
 //                check values against rules
               while ($dataaction=$DB->fetchAssoc($resultaction)) {
                  if (substr($dataaction['field'],0,8) == 'session_') {
                     switch ($dataaction['field']) {
                        case "session_users_id":
                           $valuetocheck = $_SESSION['glpiID'];
                           $comparisonoperation = $dataaction['action_type'];
                           break 1;
                        case "session_groups_id":
                           $arraytocheck = [];
                           $arraytocheck = $_SESSION['glpigroups'];
                           $comparisonoperation =
$dataaction['action_type']."inarray";
                           break 1;
                     }
                     $fieldtocheck = substr($dataaction['field'],8);
                  } else {
                     if (is_array($item)) {
                        $valuetocheck = $item[$dataaction['field']];
                     } else if (isset($item->input[$dataaction['field']]))
                        {
                           $valuetocheck = $item->input[$dataaction['field']];
                        }
                        else
                        {
                           $valuetocheck = $item->fields[$dataaction['field']];
                        }
                     $fieldtocheck = $dataaction['field'];
                     $comparisonoperation = $dataaction['action_type'];
                  }
                  switch ($comparisonoperation) {
                     case "isempty":
                        if (substr($dataaction['field'],-3) == '_id') {
                           $actioncheck = ($valuetocheck==0?true:false);
                        } else {
                           $actioncheck = ($valuetocheck==""?true:false);
                        }
                     break 1;
                     case "isnotempty":
                        if (substr($dataaction['field'],-3) == '_id') {
                           $actioncheck = ($valuetocheck!=0?true:false);
                        } else {
                           $actioncheck = ($valuetocheck!=""?true:false);
                        }
                     break 1;
                     case "is":
                        $actioncheck =
($valuetocheck==html_entity_decode($dataaction['value'])?true:false);
                     break 1;
                     case "isnot":
                        $actioncheck =
($valuetocheck!=html_entity_decode($dataaction['value'])?true:false);
                     break 1;
                     case "isinarray":
                        $actioncheck =
in_array(html_entity_decode($dataaction['value']),$arraytocheck);
                     break 1;
                     case "isnotinarray":
                        $actioncheck =
!in_array(html_entity_decode($dataaction['value']),$arraytocheck);
                     break 1;
                     case "regex_check":
                        $actioncheck =
preg_match(html_entity_decode($dataaction['value']),$valuetocheck);
                     break 1;
                     default:
                     break 1;
                  }
                  if (!$actioncheck) {
                     if (is_array($item)) {
                        $item['hookerror'] = true;
                        if (substr($fieldtocheck,-3) == '_id') {
                           $ruleactions_value =
trim(strip_tags(html_entity_decode(Dropdown::getDropdownName('glpi_'.substr($fieldtocheck,0,strlen($fieldtocheck)-3),$dataaction['value']))));
                        }
                        else {
                           $ruleactions_value = $dataaction['value'];
                        }
                        $ruleactions_label =
$fields[$dataaction['field']]['name'];
                        if (isset($item['hookmessage'])) {
                           $item['hookmessage'] .= ";".__("Rule")."
'$rules_name' ($rules_id) : ".__("Field")." '".$ruleactions_label."'
".__("is not compliant with the rule")." :
".$dataaction['action_type']." ".$ruleactions_value;
                        }
                        else {
                           $item['hookmessage'] = __("StateCheck
Rules")." :;".__("Rule")." '$rules_name' ($rules_id) : ".__("Field")."
'".$ruleactions_label."' ".__("is not compliant with the rule")." :
".$dataaction['action_type']." ".$ruleactions_value;
                        }
                     } else {
                        $item->hookerror = true;
                        if (substr($fieldtocheck,-3) == '_id') {
                           $ruleactions_value =
strip_tags(html_entity_decode(Dropdown::getDropdownName('glpi_'.substr($fieldtocheck,0,strlen($fieldtocheck)-3),$dataaction['value'])));
                        }
                        else {
                           $ruleactions_value = $dataaction['value'];
                        }
                        $ruleactions_label =
$fields[$dataaction['field']]['name'];
                        if (isset($item->hookmessage)) {
                           $item->hookmessage .= ";".__("Rule")."
'$rules_name' ($rules_id) : ".__("Field")." '".$ruleactions_label."'
".__("is not compliant with the rule")." :
".$dataaction['action_type']." ".$ruleactions_value;
                        }
                        else {
                           $item->hookmessage = __("StateCheck
Rules")." :;".__("Rule")." '$rules_name' ($rules_id) : ".__("Field")."
'".$ruleactions_label."' ".__("is not compliant with the rule")." :
".$dataaction['action_type']." ".$ruleactions_value;
                        }
                     }
                  }
               }
            }
         }
      }

      if (is_array($item)) {
         if($item['hookerror']) {
            //Session::addMessageAfterRedirect(str_replace(";","<br/>",$item['hookmessage'])."<br/><font
color='red'>".__(" Record not inserted or updated")."</font>", false,
ERROR);
            $item['input'] = false; // do not insert or update

            $this->results['status']                     = self::FAILED;
                 $this->results[self::ACTION_CHECK]['status'] = self::FAILED;
            return $this->results;
         } else {
            unset ($item['hookerror'],$item['hookmessage']);
         }
      } else {
         if($item->hookerror) {
            //Session::addMessageAfterRedirect(str_replace(";","<br/>",$item->hookmessage)."<br/><font
color='red'>".__(" Record not inserted or updated")."</font>", false,
ERROR);
            $item->input = false; // do not insert or update

            $this->results['status']                     = self::FAILED;
                 $this->results[self::ACTION_CHECK]['status'] = self::FAILED;
                 return $this->results;
         } else {
            unset ($item->hookerror,$item->hookmessage);
         }
      }

   }

     /*-------------------------------------------------------------------------------------------------
         END DATAINJECTION INTEGRATION WITH STATECHECK
     -------------------------------------------------------------------------------------------------*/




   //Manage fields belonging to relations between tables
   $this->manageRelations();

   $accepted = $this->processDictionnariesIfNeeded();

   //Get real value for fields (ie dropdown, etc)
   $this->manageFieldValues();

   //Check if the type to inject requires additional fields
   //(for example to link it with another type)
   if (!$this->areTypeMandatoryFieldsOK($this->injectionClass)) {
      $process                                     = false;
      $this->results['status']                     = self::FAILED;
      $this->results[self::ACTION_CHECK]['status'] = self::FAILED;

   } else {
      //Check is data to be inject still exists in DB (update) or not (add)
      $this->dataAlreadyInDB($this->injectionClass, $this->primary_type);
      $process = true;

      //No item found in DB
      if ($this->getValueByItemtypeAndName($this->primary_type, 'id')
== self::ITEM_NOT_FOUND) {
         //Can add item ?
         $this->results['type'] = self::IMPORT_ADD;
         if (!$accepted) {
            $this->results['status'] = self::ERROR_IMPORT_REFUSED;
            $process = false;
         } else {
            if ($this->rights['can_add']) {
               $add = true;
               $this->unsetValue($this->primary_type, 'id');
            } else {
               $process = false;
               $this->results['status'] = self::ERROR_CANNOT_IMPORT;
            }
         }

      } else { //Item found in DB
         $this->results['type'] = self::IMPORT_UPDATE;
         $this->results[$this->primary_type]
                     =
$this->getValueByItemtypeAndName($this->primary_type, 'id');

         if ($this->rights['can_update']) {
            $add = false;
         } else {
            $process = false;
            $this->results['status'] = self::ERROR_CANNOT_UPDATE;
         }
      }
   }

   if ($process) {
      //First : reformat data
      $this->reformat();

      //Second : check data
      $this->check();
      if ($this->results['status'] != self::FAILED) {
         //Third : inject data
         $item = $this->getItemInstance();
         $item->getEmpty();

         //Add important fields for injection
         $this->addNecessaryFields();

         //Add aditional infos
         $this->addOptionalInfos();

         //Manage template only when adding an item
         if ($this->results['type'] == self::IMPORT_ADD) {
            //If needed, manage templates
            $this->addTemplateFields($this->primary_type);
         }
         $values = $this->getValuesForItemtype($this->primary_type);
         $newID  = $this->effectiveAddOrUpdate($this->injectionClass,
$item, $values, $add);

         if (!$newID) {
            $this->results['status'] = self::WARNING;

         } else {
            //Store id of the injected item
            $this->setValueForItemtype($this->primary_type, 'id', $newID);

            //If type needs it : process more data after type import
            $this->processAfterInsertOrUpdate($this->injectionClass, $add);
            //$this->results['status'] = self::SUCCESS;
            $this->results[get_class($item)] = $newID;

            //Process other types

            //change order of items if needed
            if(isset($this->values['NetworkPort']) &&
isset($this->values['NetworkName'])){
               $np = $this->values['NetworkPort'];
               unset($this->values['NetworkPort']);
               $this->values = array('NetworkPort' => $np) + $this->values;
            }

            foreach ($this->values as $itemtype => $data) {
               //Do not process primary_type

               if ($itemtype != get_class($item)) {
                  $injectionClass = self::getInjectionClassInstance($itemtype);
                  $item           = new $itemtype();

                  $this->addNeededFields($injectionClass, $itemtype);
                  $this->dataAlreadyInDB($injectionClass, $itemtype);

                  if ($this->getValueByItemtypeAndName($itemtype,
'id') == self::ITEM_NOT_FOUND) {
                     $add = true;
                     $this->unsetValue($itemtype, 'id');
                  } else {
                     $add = false;
                  }
                  $values = $this->getValuesForItemtype($itemtype);
                  if ($this->lastCheckBeforeProcess($injectionClass, $values)) {
                     $tmpID  =
$this->effectiveAddOrUpdate($injectionClass, $item, $values, $add);
                     $this->processAfterInsertOrUpdate($injectionClass, $add);
                  }
               }
            }
         }
      }
   }
   return $this->results;
}

$firstKey is the class of the object.
$currentValues is the array of the key->values of the object with its key
equals to the database fields.

Then, I fix your queries in order to work into the Data Injection plugin
(e.g. LIKE instead = in frontname due to Computer and not computer) and
copy and paste your "core logical code" into the method that is the same.

then, I put the result into their $this->results so I get the error lines
in the result set.
---------------------

Hope you enjoyed the read. I started to study GLPI plugins 3 days ago and
I'm not so confident and I've never studied PHP.

*QUESTION:*
*IT IS POSSIBLE TO PROVIDE AN HOOK INTO YOUR CODE THAT TAKES AS PARAMETER
AN ARRAY AND PERFORM THE CHECKS AND RETURN TRUE OR FALSE?*

THE ARRAY IN INPUT:

{
     "ClassName": {"key1": "value1", "key2": "value2", ...}
}

but if you use my adjustment it should work!
---

I hope you answer me soon because I'm working on a critical project.


THANK YOU SO MUCH FOR ALL.
Best Regards,

Maurizio Natalia


Il giorno sab 7 ott 2023 alle ore 12:01 Eric Feron ***@***.***>
ha scritto:

**Comment by maunat** [comment]
Hi, another action I did it has been to add a Warn Popup boolean in order
to show or not the !! Highlighted fields are controlled !!

You can find the code here below:

*setup.php*

function hook_pre_item_form(array $params) {
   global $DB, $_SERVER;
    // check that the current form is listed for statecheck
   if (isset($_SERVER['HTTP_REFERER'])) {
      $start = strpos($_SERVER['HTTP_REFERER'],'/front') + 7;
      $end = strpos($_SERVER['HTTP_REFERER'],'.',$start);
      $frontname = substr($_SERVER['HTTP_REFERER'],$start,$end-$start);

      # ---> this is the control to support Custom Objects!
      if($frontname == 'object') {
            parse_str(parse_url($_SERVER['HTTP_REFERER'])['query'], $output);
            $classname = $output['itemtype'];
            if (isset($classname)) {
                $frontname = $classname;
            }
        }

        $dbu = new DbUtils();
      if ($dbu->countElementsInTable('glpi_plugin_statecheck_tables',
['frontname' => $frontname])) {

            $query = "SELECT `glpi_plugin_statecheck_tables`.`id`,
`glpi_plugin_statecheck_rules`.`plugin_statecheck_tables_id`,
`glpi_plugin_statecheck_rules`.`is_active_warn_popup` as
isActiveWarnPopup FROM `glpi_plugin_statecheck_tables`,
`glpi_plugin_statecheck_rules` WHERE
`glpi_plugin_statecheck_tables`.`id` =
`glpi_plugin_statecheck_rules`.`plugin_statecheck_tables_id` AND
`glpi_plugin_statecheck_tables`.`frontname` = '".$frontname."'";

          if ($resultstate=$DB->query($query)) {
                if ($datastate=$DB->fetchAssoc($resultstate)) {
                    $isActiveWarnPopup = $datastate['isActiveWarnPopup'];
                    if (isset($isActiveWarnPopup) && $isActiveWarnPopup) {
                        Session::addMessageAfterRedirect('<font
color="red"><b>'.__('!! Highlighted fields are controlled
!!').'</b></font>');
                        Html::displayMessageAfterRedirect();
                    }
                }
            }

      }
   }
}

*rule.class.php*

$tab[9]['table']           = $this->getTable();
$tab[9]['field']           = 'is_active_warn_popup';
$tab[9]['name']            = __('Warn Popup', 'statecheck');
$tab[9]['datatype']        = 'bool';

$tab[] = [
         'id'       => '9',
         'table'    => $this->getTable(),
         'field'    => 'is_active_warn_popup',
         'name'     => __('Warn Popup', 'statecheck'),
         'datatype' => 'bool'
      ];

echo "<tr class='tab_bg_1'>";
echo "<td>".__('Warn Popup', 'statecheck')."</td>";
echo "<td>";
Dropdown::showYesNo("is_active_warn_popup",
$this->fields["is_active_warn_popup"]);
echo "</td></tr>\n";


CREATED NEW: *empty-1.0.2.sql*

DROP TABLE IF EXISTS `glpi_plugin_statecheck_rules`;
CREATE  TABLE `glpi_plugin_statecheck_rules` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Internal ID' ,
  `entities_id` INT(11) NOT NULL default '0',
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plugin_statecheck_tables_id` INT(11) NOT NULL default '0',
  `plugin_statecheck_targetstates_id` INT(11) NOT NULL default '0',
  `ranking` int(11) NOT NULL DEFAULT '0',
  `match` char(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT
'see define.php *_MATCHING constant',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',

# here the new key ------------------------------------------------
  `is_active_warn_popup` tinyint(1) NOT NULL DEFAULT '0',

#------------------------------------------------------------------
  `comment` text COLLATE utf8mb4_unicode_ci,
  `successnotifications_id` INT(11) NOT NULL default '0' COMMENT
'notification in case of success',
  `failurenotifications_id` INT(11) NOT NULL default '0' COMMENT
'notification in case of failure',
  `date_mod` datetime DEFAULT NULL,
  `is_recursive` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `entities_id` (`entities_id`),
  KEY `plugin_statecheck_tables_id` (`plugin_statecheck_tables_id`),
  KEY `plugin_statecheck_targetstates_id` (`plugin_statecheck_targetstates_id`),
  KEY `is_active` (`is_active`),
  KEY `name` (`name`),
  KEY `date_mod` (`date_mod`),
  KEY `is_recursive` (`is_recursive`)
) AUTO_INCREMENT=34
DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ;


*hook.php*

$DB->runFile(Plugin::getPhpDir("statecheck")."/sql/empty-1.0.2.sql");



*The result:*

[image: image.png]

Maurizio


Il giorno sab 7 ott 2023 alle ore 12:01 Eric Feron ***@***.***>
ha scritto:

**Comment by maunat** [comment]
Hi Eric,

I reached a stable new version but I need your help to release it in the
GLPI marketplace.
Could we arrange a tech meeting or can I push the code in a separate branch
in order to review it?

Thank you,

Maurizio

Il giorno sab 7 ott 2023 alle ore 15:32 Maurizio Natalia <
***@***.***> ha scritto:
