### ISSUE TITLE
Example for setting up mandatory fields in Inventory

### ISSUE THREAD

**Issue by Giudy** [ericferon/glpi-statecheck#26]
Hi, 
 I'm stryggling trying to set a field mandatory in the Inventory. It is just a simple check by maybe I'm missing a step or I have misnderstood how the plugin wors:
1. create the table: the field I wannadefine mandatory is (for example UUID). So for the peripherals I have, as there are no states

![immagine](https://github.com/ericferon/glpi-statecheck/assets/7987648/8d9cbdfd-a0f0-4a54-81d5-b334c2f0e667)

But hten the Rule doesn't allow me to select the UUID as mandatory

wher eis the trick?

thank you

**Comment by ericferon** [comment]
Hi,
Unfortunately, UUID is not in the list of searchable fields and my plugin gets the same dropdown list as the searchable fields.
K.r,
