### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by igortereshchenko** [ericferon/glpi-statecheck#3]
At the end of the file GLPI_ROOT/plugins/**yourplugin**/hook.php, add the following line : include_once(GLPI_ROOT . "/plugins/statecheck/hookinclude.php");
In GLPI_ROOT/plugins/yourplugin/inc/yourclass.class.php,

For me it is not clear the way to install it. What you mean **yourplugin**?
I have no other plugins at all and want to install only your one.

Thanks for help

**Comment by ericferon** [comment]
I've developed and used the statecheck plugin with the "dataflows" plugin. So the README file has been written with that experience.
I have to check and test how to install the statecheck plugin when you want to use it on GLPI core tables.
On which class do you intend to use statecheck plugin ?
I'm on holiday during the next week. So do not expect an answer too soon.

**Comment by ericferon** [comment]
A new version has just been released, able to cope with core assets (not only plugin assets)
Best regards,
