### ISSUE TITLE
No package to install directly from the release page.

### ISSUE THREAD

**Issue by Wolvverine** [ericferon/glpi-statecheck#7]
https://github.com/ericferon/glpi-statecheck/releases
there is no archive with the plugin version for direct download in a given version and unpacking directly  to the plugins directory in GLPI.

E.g. like here:
https://github.com/fusioninventory/fusioninventory-for-glpi/releases

  where it is ready to be installed directly from the network package:

https://github.com/fusioninventory/fusioninventory-for-glpi/releases/download/glpi9.3%2B1.1/fusioninventory-9.3.1.1.tar.bz2

This makes it difficult for example to install / update automatically when re-installing glpi in docker containers.

**Comment by ericferon** [comment]
I have added a tar.gz file as binary to the release.
But as explained for the archisw plugin, this is not automated in the release process of Github.
So, I cannot do it for each release.
Best regards,
