### ISSUE TITLE
php error?

### ISSUE THREAD

**Issue by Stoatwblr** [ericferon/glpi-statecheck#9]
I keep getting error messages like this pointing back to Statecheck profile.class.php:216

Not sure if it's serious or not, but the logfiles are getting a bit full.

2019-01-24 13:32:36 [11@msslyz.mssl.ucl.ac.uk]
  Backtrace :
  inc/toolbox.class.php:562                          Toolbox::backtrace()
  inc/dbutils.class.php:323                          Toolbox::deprecated()
  inc/db.function.php:178                            DbUtils->countElementsInTable()
  plugins/statecheck/inc/profile.class.php:216       countElementsInTable()
  inc/plugin.class.php:800                           PluginStatecheckProfile::initProfile()
  front/plugin.form.php:47                           Plugin->activate()
[2019-01-24 13:32:36] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): Declaration of PluginStatecheckRule::executePluginsActions($action, $output, $params) should be compatible with Rule::executePluginsActions($action, $output, $params, array $input = Array)
  Backtrace :
  inc/autoload.function.php:365
  inc/autoload.function.php:365                      include_once()
  :                                                  glpi_autoload()
  plugins/statecheck/inc/menu.class.php:40           spl_autoload_call()
  inc/html.class.php:1426                            PluginStatecheckMenu::getMenuContent()
  inc/html.class.php:6190                            Html::generateMenuSession()
  inc/html.class.php:1530                            Html::displayMainMenu()
  front/plugin.php:89                                Html::header()
  {"user":"11@msslyz.mssl.ucl.ac.uk"}
[2019-01-24 13:32:36] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): Declaration of PluginStatecheckRule::executeActions($output, $params) should be compatible with Rule::executeActions($output, $params, array $input = Array)
  Backtrace :
  inc/autoload.function.php:365
  inc/autoload.function.php:365                      include_once()
  :                                                  glpi_autoload()
  plugins/statecheck/inc/menu.class.php:40           spl_autoload_call()
  inc/html.class.php:1426                            PluginStatecheckMenu::getMenuContent()
  inc/html.class.php:6190                            Html::generateMenuSession()
  inc/html.class.php:1530                            Html::displayMainMenu()
  front/plugin.php:89                                Html::header()
  {"user":"11@msslyz.mssl.ucl.ac.uk","mem_usage":"0.000\", 8.37Mio)"}

**Comment by ericferon** [comment]
Indeed, the call to  countElementsInTable was erroneous.
It's solved in v2.0.10.
Thank you for your contribution,
